apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: app-auth
  template:
    metadata:
      labels:
        app: app-auth
    spec:
      containers:
        - name: auth
          image: amirjfr/kub-demo-auth
          imagePullPolicy: Always

