apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: app-users
  template:
    metadata:
      labels:
        app: app-users
    spec:
      containers:
        - name: users
          image: amirjfr/kub-demo-user
          imagePullPolicy: Always
        - name: auth
          image: amirjfr/kub-demo-auth
          imagePullPolicy: Always
