apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: app-users
  template:
    metadata:
      labels:
        app: app-users
    spec:
      containers:
        - name: users
          image: amirjfr/kub-demo-user
          imagePullPolicy: Always
          env:
            - name: AUTH_URL
              # value: localhost # IMPORTANT; in the same pod two containers can connect using localhost

